#!/usr/bin/env python3
"""
sb-creator-pptx — Inject HTML→Editable PPTX export logic into a target HTML.

Two placements are supported:
  - "cover" : insert the PPTX button INSIDE the existing `.download-btns` div
              of the cover page (right next to the PDF button).
              Used when the target was generated by sb-creator.
  - "fixed" : insert a fixed top-right wrapper containing the PPTX button.
              Fallback for HTMLs that have no `.download-btns` div.

Default placement is "auto": cover if `.download-btns` is detected, else fixed.

Usage:
    python3 inject.py <html_path>
        [--selector .screen-section]
        [--slide-width 13.33]
        [--slide-height 7.5]
        [--output-name <basename>]       # default: <html_basename>_editable
        [--placement {auto,cover,fixed}] # default: auto
        [--no-backup]
        [--no-button]                    # script only, no UI button
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = SKILL_DIR / "scripts"

# Button block (sits inside .download-btns when placement=cover, else before </body>)
BTN_MARKER_START = "<!-- BEGIN sb-creator-pptx button (auto-injected) -->"
BTN_MARKER_END = "<!-- END sb-creator-pptx button -->"

# Script block (always before </body>)
SCR_MARKER_START = "<!-- BEGIN sb-creator-pptx script (auto-injected) -->"
SCR_MARKER_END = "<!-- END sb-creator-pptx script -->"

# Legacy single-block markers (pre-2026-05). Stripped on re-inject for back-compat.
LEGACY_MARKER_START = "<!-- BEGIN sb-creator-pptx (auto-injected) -->"
LEGACY_MARKER_END = "<!-- END sb-creator-pptx -->"

DOWNLOAD_BTNS_RE = re.compile(
    r'(<div\s+class="download-btns(?:\s+[^"]*)?"[^>]*>)(.*?)(</div>)',
    re.DOTALL,
)


def render_template(template: str, selector: str, slide_w: float, slide_h: float, out_name: str) -> str:
    return (template
            .replace("__SECTION_SELECTOR__", selector)
            .replace("__SLIDE_WIDTH__", f"{slide_w}")
            .replace("__SLIDE_HEIGHT__", f"{slide_h}")
            .replace("__OUTPUT_NAME__", out_name))


def detect_placement(html: str, requested: str) -> str:
    if requested != "auto":
        return requested
    return "cover" if DOWNLOAD_BTNS_RE.search(html) else "fixed"


def build_button_block(placement: str) -> str:
    if placement == "cover":
        snippet = (SCRIPTS_DIR / "button-snippet-cover.html").read_text(encoding="utf-8").rstrip()
    else:
        snippet = (SCRIPTS_DIR / "button-snippet-fixed.html").read_text(encoding="utf-8").rstrip()
    return f"{BTN_MARKER_START}\n{snippet}\n{BTN_MARKER_END}"


def build_script_block(selector: str, slide_w: float, slide_h: float, out_name: str) -> str:
    js_template = (SCRIPTS_DIR / "pptx-export.js").read_text(encoding="utf-8")
    js = render_template(js_template, selector, slide_w, slide_h, out_name)
    return f"{SCR_MARKER_START}\n<script>\n{js}\n</script>\n{SCR_MARKER_END}"


def strip_existing(html: str) -> str:
    """Remove any previously injected blocks (current + legacy markers)."""
    patterns = [
        re.compile(re.escape(BTN_MARKER_START) + r".*?" + re.escape(BTN_MARKER_END) + r"\n?", re.DOTALL),
        re.compile(re.escape(SCR_MARKER_START) + r".*?" + re.escape(SCR_MARKER_END) + r"\n?", re.DOTALL),
        re.compile(re.escape(LEGACY_MARKER_START) + r".*?" + re.escape(LEGACY_MARKER_END) + r"\n?", re.DOTALL),
    ]
    for p in patterns:
        html = p.sub("", html)
    return html


def insert_button_cover(html: str, button_block: str) -> str:
    """Insert button block just before the closing </div> of `.download-btns`."""
    def _sub(m):
        opening, inner, closing = m.group(1), m.group(2), m.group(3)
        return f"{opening}{inner.rstrip()}\n      {button_block}\n    {closing}"
    new_html, n = DOWNLOAD_BTNS_RE.subn(_sub, html, count=1)
    if n == 0:
        raise RuntimeError("placement=cover but no `.download-btns` div found")
    return new_html


def insert_block_before_body_end(html: str, block: str) -> str:
    matches = list(re.finditer(r"</body\s*>", html, re.IGNORECASE))
    if not matches:
        return html.rstrip() + "\n" + block + "\n"
    last = matches[-1]
    return html[:last.start()] + block + "\n" + html[last.start():]


def main():
    ap = argparse.ArgumentParser(description="Inject HTML→Editable PPTX export into an HTML file.")
    ap.add_argument("html_path", help="Target HTML file path")
    ap.add_argument("--selector", default=".screen-section",
                    help="CSS selector for slide sections (default: .screen-section)")
    ap.add_argument("--slide-width", type=float, default=13.33,
                    help="Slide width in inches (default: 13.33)")
    ap.add_argument("--slide-height", type=float, default=7.5,
                    help="Slide height in inches (default: 7.5)")
    ap.add_argument("--output-name", default=None,
                    help="Output PPTX basename (no .pptx). Default: <html_basename>_editable")
    ap.add_argument("--placement", choices=["auto", "cover", "fixed"], default="auto",
                    help="Where to place the PPTX button. 'auto' picks 'cover' if "
                         "`.download-btns` exists, else 'fixed' (default: auto)")
    ap.add_argument("--no-backup", action="store_true", help="Skip creating .bak.html backup")
    ap.add_argument("--no-button", action="store_true", help="Inject script only, no UI button")
    args = ap.parse_args()

    target = Path(args.html_path).resolve()
    if not target.exists():
        print(f"ERROR: file not found: {target}", file=sys.stderr)
        sys.exit(1)
    if target.suffix.lower() not in (".html", ".htm"):
        print(f"WARNING: target is not .html/.htm: {target.suffix}", file=sys.stderr)

    out_name = args.output_name or (target.stem + "_editable")

    if not args.no_backup:
        backup = (target.with_suffix(target.suffix + ".bak.html")
                  if not target.suffix.endswith(".bak.html")
                  else target.with_name(target.name + ".bak"))
        shutil.copy2(target, backup)
        print(f"backup: {backup.name}")

    html = target.read_text(encoding="utf-8")
    original_len = len(html)
    html = strip_existing(html)
    print("existing injection: " + ("replaced" if len(html) < original_len else "none → new insert"))

    placement = detect_placement(html, args.placement)

    # Always insert the script block before </body>
    script_block = build_script_block(args.selector, args.slide_width, args.slide_height, out_name)
    html = insert_block_before_body_end(html, script_block)

    # Insert the button block (cover-inline or fixed top-right)
    if not args.no_button:
        button_block = build_button_block(placement)
        if placement == "cover":
            try:
                html = insert_button_cover(html, button_block)
            except RuntimeError as err:
                print(f"WARN: {err} → falling back to fixed placement", file=sys.stderr)
                placement = "fixed"
                button_block = build_button_block(placement)
                html = insert_block_before_body_end(html, button_block)
        else:
            html = insert_block_before_body_end(html, button_block)

    target.write_text(html, encoding="utf-8")

    print(f"injected → {target.name}")
    print(f"  selector       : {args.selector}")
    print(f"  slide size     : {args.slide_width} x {args.slide_height} in")
    print(f"  output pptx    : {out_name}.pptx")
    print(f"  placement      : {placement}")
    print(f"  button         : {'on' if not args.no_button else 'off'}")
    if placement == "cover":
        print("\nNext: 브라우저에서 HTML을 열면 표지 우측 상단에 PDF · PPTX 버튼이 함께 표시됩니다.")
    else:
        print("\nNext: 브라우저에서 HTML을 열고 우상단 'PPTX 다운로드' 버튼 클릭")


if __name__ == "__main__":
    main()
